#图片目录配置
image_dir : static/images/

favicon: favicon.png

sidebar_behavior: 1

#sidebar_bg: cover.jpg

#用户配置
author:
    #用户名称
    name: bukas
    #用户头像
    gravatar: gravatar.png

disqus_shortname: bukas
duoshuo_shortname: yhzblog
#swiftype_install_key: w8FFTKFNZed2tJN2ZA6p

# Analytics
google_analytics:
    id: UA-49034721-1
    site: w3cboy.com

#侧栏配置
#以下配置均无容错处理，大家都是程序员，配置错误请不要找作者。
sidebar:
    menu:
        home:
            title: global.home
            url: /
            icon: home
        # categories:
        #     title: global.categories
        #     url: /categories
        #     icon: bookmark
        archives:
            title: global.archives
            url: /archive/
            icon: archive
        tags:
            title: global.tags
            url: /tags/
            icon: tags
        # search:
        #     title: global.search
        #     url: /#search
        #     icon: search
        #     class: st-search-show-outputs
        about:
            title: global.about
            url: /about/
            icon: user
        # links:
        #    title: global.link
        #    url: /links/
        #    icon: link
    author_links:
        github:
            title: global.github
            url: https://github.com/huanz
            icon: github
        # stack_overflow:
        #     title: global.stack_overflow
        #     url: http://stackoverflow.com/users
        #     icon: stackoverflow
        # twitter:
        #     title: global.twitter
        #     url: https://twitter.com/
        #     icon: twitter
        weibo:
            title: global.weibo
            url: http://weibo.com/2335228667/
            icon: weibo
        # weixin:
        #     title: global.weixin
        #     url: https://weixin.com/
        #     icon: weixin
        # facebook:
        #     title: global.facebook
        #     url: https://facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: global.google_plus
        #     url: https://plus.google.com/
        #     icon: googleplus
        # linked_in:
        #     title: global.linkedin
        #     url: https://www.linkedin.com/profile/
        #     icon: linkedin
        # mail:
        #     title: global.mail
        #     url: mailto
        #     icon: mail
    rss:
        rss:
            title: global.rss
            url: /w3cboy.xml
            icon: rss